[package]
name = "remu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
elf = "0.7.1"
fnv = "1.0.7"
log = "0.4.17"
num-derive = "0.4.0"
num-traits = "0.2.16"
thiserror = "1.0.49"
